theme: Cayman theme
title: Witam na mojej stronie!
description: Nazywam się Maciej Gumiela, jestem obecnie (oby jeszcze trochę) studentem Akademii Górniczo-Hutniczej w Krakowie. Do moich zainteresowań należą sport, gotowanie i podróże.
